#: kivy 1.11.1
#:import Gauge kivy.garden.gauge

<VehicleSpeed>:
    FloatLayout:
	    SpeedMeter:
	    	size_hint: (0.3, 0.5)
	    	pos_hint: {'x':0.15, 'y':0.25}
	    	#pos: (10,20)
	        id: speed
	        max: 120
	        tick: 20
	        start_angle: -120
	        end_angle: 120
	        subtick: 5
	        label: 'Km/h'
	        value: app.speed
	        cadran_color: '#0f0f0f'
	        needle_color: '#ff0000'
	        sectors: (0, '#ffffff')